In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
list = [1, 2, 3, 5, 7, 12]
a = np.array(list)
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
a[2]

np.int64(3)

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional arrays

In [3]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]
list_3 = [7, 8, 9]
n = np.array([list_1, list_2, list_3])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
n[0, 2]

np.int64(3)

In [7]:
n[0, 2] = 10
n

array([[ 1,  2, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [10]:
n[1]
# passing one index --> getting entire row

array([4, 5, 6])

In [11]:
n[1] = 1
# changing for one index --> changing entire row
n

array([[ 1,  2, 10],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [13]:
n[:, 1]
# second column

array([2, 1, 8])

In [14]:
n[:, 1] = 0
n

array([[ 1,  0, 10],
       [ 1,  0,  1],
       [ 7,  0,  9]])

## Randomly generated arrays

In [15]:
np.random.rand(5, 2)

array([[0.11925833, 0.13827044],
       [0.78958067, 0.70595471],
       [0.69928342, 0.11241279],
       [0.86925735, 0.14831321],
       [0.25414155, 0.72893495]])

In [4]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [5]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [6]:
# Element-wise addition
a = a + 1
a

array([1, 2, 3, 4, 5])

In [7]:
# Element-wise multiplication
a = a * 2
a

array([ 2,  4,  6,  8, 10])

In [8]:
# Combinations
b = (10 + (a * 2)) ** 2 / 100
b

array([1.96, 3.24, 4.84, 6.76, 9.  ])

In [9]:
# Element-wise addition of two arrays
c = a + b
c

array([ 3.96,  7.24, 10.84, 14.76, 19.  ])

## Comparison operations

In [11]:
a >= 5

array([False, False,  True,  True,  True])

In [13]:
b >= a

array([False, False, False, False, False])

In [14]:
# Select elements for which condition is true
a[a >= 5]

array([ 6,  8, 10])

## Summarizing operations

In [15]:
a.min()

np.int64(2)

In [17]:
sum = a.sum()
sum

np.int64(30)

In [19]:
mean = a.mean()
mean

np.float64(6.0)

In [20]:
std = a.std()
std

np.float64(2.8284271247461903)