In [2]:
import numpy as np

## Vector operations

In [5]:
u = np.array([2, 4, 5, 6])
print(u)
u * 2

[2 4 5 6]


array([ 4,  8, 10, 12])

In [6]:
# Addition works element-wise
v = np.array([1, 0, 0, 2])
u + v

array([3, 4, 5, 8])

## Multiplication

### Vector-vector multiplication

In [8]:
# Element-wise multiplication
u * v

array([ 2,  0,  0, 12])

In [10]:
# Dot product multiplication (u.v = sum (ui*vi) for all i

def dot_product(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [11]:
dot_p = dot_product(u, v)
dot_p

np.float64(14.0)

In [12]:
u.dot(v)

np.int64(14)

### Matrix-vector multiplication

In [13]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
U.shape

(3, 4)

In [15]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = dot_product(U[i], v)

    return result

In [16]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [17]:
U.dot(v)

array([14,  5,  5])

### Matrix-matrix multiplication

In [18]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
    ])

In [19]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [20]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [21]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [23]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Inverse matrix

In [26]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [28]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [30]:
res = Vs.dot(Vs_inv)
res

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])