In [2]:
import pandas as pd
import numpy as np

## Q1: Pandas version

In [3]:
# Pandas version
pd.__version__

'3.0.6'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

## Q2: Records count

In [12]:
print(f"There are a total of: {df.shape[0]} records.")

There are a total of: 10000 records.


## Q3: Fuel types

In [14]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [25]:
print(f"There are a total of: {df['fuel_type'].unique().size} unique fuel types.")

There are a total of: 3 unique fuel types.


## Q4: How many columns in the dataset have missing values

In [27]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

We see that two columns have missing values

## Q5: Max fuel efficiency

In [29]:
print(f"Maximum fuel efficiency: {df['fuel_efficiency_mpg'].max()} mpg.")

Maximum fuel efficiency: 41.2 mpg.


## Q6 Median value of horsepower

In [30]:
median = df['horsepower'].median()
print(median)

254.0


In [34]:
df['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ... 
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

Most frequent value of horsepower is 252.0

Now, we will replace the nan on the column with the most frequent value.

In [35]:
df['horsepower_v2'] = df['horsepower']

In [39]:
df['horsepower_v2'].fillna(value=252.0, inplace=True, limit=None)

/tmp/ipykernel_2997/3771545915.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['horsepower_v2'].fillna(value=252.0, inplace=True, limit=None)


0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...  
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower_v2, Length: 10000, dtype: float64

In [40]:
df['horsepower_v2'].median()

np.float64(254.0)

Value for median has not changed.

## Q7: Sum of weights

In [41]:
df['origin'].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [56]:
# Numpy matrix X
X = df[df['origin']=='Asia'][:7][['vehicle_weight','model_year']].to_numpy()

In [57]:
# View matrix
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [58]:
# Test X transpose
X.T

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [69]:
# Calculation of X transpose * X
XTX = (X.T).dot(X)

In [71]:
# Verify that XTX is square
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [72]:
# Inverse matrix
XTX_inv = np.linalg.inv(XTX)

In [73]:
# Verify that XTX_inv is indeed the inverse of XTX (product is I)
XTX_inv.dot(XTX)

array([[ 1.00000000e+00, -7.77917769e-15],
       [-8.75935812e-14,  1.00000000e+00]])

In [74]:
# Create array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [75]:
# Calculate w
w = (XTX_inv.dot(X.T)).dot(y)

In [76]:
w

array([0.13644777, 0.2327492 ])

In [78]:
# Solution
w.sum()

np.float64(0.36919696904925486)